import {
  createContext,
  useContext,
  useState,
  useEffect,
  ReactNode,
} from "react";

type Language = "en" | "te";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    dashboard: "Dashboard",
    transactions: "Transactions",
    suppliers: "Suppliers",
    expenditures: "Expenditures",
    bills: "Bills",
    reports: "Reports",
    settings: "Settings",
    admin: "Administration",
    sales: "Sales History",

    // Navigation & Header Extra
    "logged-in-as": "Logged in as",
    "sign-out": "Sign out",
    "mobile-tracker": "Mobile Repair Tracker",
    "professional-management": "Professional Repair Management",
    "system-online": "System Online",
    "profile": "Profile",
    "log-out": "Log out",

    // Dashboard
    "today-revenue": "Today's Revenue",
    "pending-repairs": "Pending Repairs",
    "quick-actions": "Quick Actions",
    "recent-transactions": "Recent Transactions",
    "new-transaction": "New Transaction",
    "record-payment": "Record Payment",
    "welcome-back": "Welcome back",
    "worker-tasks": "Here are your daily tasks.",
    "shop-overview": "Here's your repair shop overview.",
    "loading": "Loading…",
    "refresh": "Refresh",
    "hide-profits": "Hide Profits",
    "show-profits": "Show Profits",
    "profit": "Profit",
    "today-earnings": "Today's earnings",
    "awaiting-completion": "Awaiting completion",
    "latest-repair-jobs": "Latest repair jobs",
    "view-all": "View All",
    "no-transactions-yet": "No transactions yet",
    "add-first-transaction": "Add your first repair transaction to get started",
    "add-transaction": "Add Transaction",

    // Transactions
    "customer-details": "Customer Details",
    "repair-info": "Repair Info",
    "parts-supplier": "Parts & Supplier",
    "additional-details": "Additional Details",
    "customer-name": "Customer Name",
    "phone-number": "Phone Number",
    "device-model": "Device Model",
    "repair-type": "Repair Type",
    "repair-cost": "Repair Cost",
    "payment-method": "Payment Method",
    "amount-given": "Amount Given",
    "change-returned": "Change Returned",
    "sno": "S.No",
    "txn-id": "Txn ID",
    "date-col": "Date",
    "customer-col": "Customer",
    "device-col": "Device",
    "cost-col": "Cost",
    "status-col": "Status",
    "actions-col": "Actions",
    "search-placeholder": "Search transactions...",
    "filter-payment": "Filter Payment",
    "all-payments": "All Payments",
    "view-details": "View Details",
    "completed": "Completed",
    "pending": "Pending",
    "cancelled": "Cancelled",
    "manage-repairs-desc": "Manage all repair transactions",
    "transaction-list": "Transaction List",
    "txns-found": "transactions found",
    "showing-pages": "Showing",
    "of-pages": "of",
    "pages-label": "pages",
    "delete-confirm": "Are you sure you want to delete this transaction? This action cannot be undone.",
    "customer-history": "Customer History",
    "parts-purchased": "Parts Purchased from Suppliers:",
    "no-parts-data": "(No parts data available in mock. Integrate with parts/supplier info if present in your data model.)",
    "copy-txn-id": "Copy transaction ID",
    "edit-txn": "Edit transaction",
    "delete-txn": "Delete transaction",

    // Admin & Logs
    "active-sessions": "Active Sessions",
    "audit-log": "Audit Log",
    "user-management": "User Management",
    "data-export": "Data Export",
    permissions: "Permissions",
    overview: "Overview",
    sessions: "Sessions",
    "change-password": "Change Password",
    appearance: "Appearance",
    system: "System",
    backend: "Backend",
    "total-revenue": "Total Revenue",
    "total-profit": "Total Profit",
    "total-transactions": "Total Transactions",
    "average-transaction-value": "Average Transaction Value",
    "completed-transactions": "Completed Transactions",
    "pending-transactions": "Pending Transactions",
    "create-user": "Create User",
    "delete-user": "Delete User",
    "no-users-found": "No users found.",
    "change-role": "Change Role",
    "never-changed": "Never changed",
    "total-users": "total",
    username: "Username",
    role: "Role",
    created: "Created",
    "last-seen": "Last seen",
    active: "Active",
    success: "Success",
    failed: "Failed",
    details: "Details",
    "ip-address": "IP Address",
    action: "Action",
    timestamp: "Timestamp",
    "export-csv": "Export CSV",
    "download-users": "Download Users",
    "download-transactions": "Download Transactions",
    "download-suppliers": "Download Suppliers",

    // Admin & Logs Extra
    "administration": "Administration",
    "full-system-control": "Full system control",
    "admin-access-required": "Admin Access Required",
    "admin-only-message": "Only administrators can access this page.",
    "logged-in-as-status": "Logged in as:",
    "stats": "Stats",
    "users": "Users",
    "perms": "Perms",
    "audit": "Audit",
    "export": "Export",
    "api-label": "API",
    "last-updated-at": "Last updated",
    "audit-desc": "Real-time security events — login attempts, password changes, role updates, and user deletions",
    "no-audit-events": "No audit events recorded yet.",
    "timestamp-col": "Timestamp",
    "action-col": "Action",
    "actor-col": "Actor",
    "target-col": "Target",
    "ip-col": "IP Address",
    "details-col": "Details",
    "end-of-trail": "• End of audit trail reached •",
    "loading-more-logs": "Loading more log entries...",
    "active-sessions-desc": "Manage currently active sessions and revoke security tokens if needed",
    "current-device": "Current Device",
    "revoke-session": "Revoke",
    "confirm-revoke": "Are you sure you want to revoke this session?",
    "all-sessions-revoked": "All sessions except current have been revoked",
    "error-loading-sessions": "Error loading sessions",
    "revoke-session-title": "Revoke Session",
    "user-mgmt-title": "User Management",
    "user-mgmt-desc": "Manage system users, reset passwords, rename, or delete accounts",

    // UserManagement inline forms
    "new-user-label": "New User",
    "create-btn": "Create",
    "username-placeholder": "Username",
    "password-placeholder": "Password (8+ chars, num, #)",
    "reset-pw-title": "Force-reset password for",
    "new-pw-placeholder": "New password (8+ chars, num, #)",
    "edit-username-title": "Edit username",
    "new-username-placeholder": "New username",
    "connection-error": "Connection Error",
    "retry": "Retry",
    "loading-users": "Loading users…",
    "pw-last-changed": "Password last changed",
    "shop-id": "Shop ID",
    "reset-password-btn": "Reset Password",
    "delete-user-btn": "Delete User",
    "change-role-btn": "Change Role",
    "confirm-delete-user": "Permanently delete",
    "confirm-delete-user-suffix": "This cannot be undone.",
    "you-label": "(you)",
    "never-seen": "Never",
    "just-now": "just now",
    "active-label": "Active",
    "retrieving-sessions": "Retrieving active sessions...",
    "no-sessions-found": "No active sessions found.",
    "revoke-session-confirm": "Revoke this session? The user will be logged out on that device.",
    "session-revoked-title": "Session revoked",
    "session-revoked-desc": "The session has been terminated successfully.",
    "session-count-suffix": "active session",
    "session-count-plural": "active sessions",
    "checked-realtime": "Checked in real-time",

        "user-mgmt-err-req": "Username and password are required",
    "user-mgmt-err-len": "Password must be at least 8 characters",
    "user-mgmt-err-num": "Password must contain at least one number",
    "user-mgmt-err-spec": "Password must contain at least one special character",
    "user-mgmt-created-title": "✅ User created",
    "user-mgmt-created-desc": "added",
    "user-mgmt-new-user": "New User",
    "user-mgmt-pw-placeholder": "Password (8+ chars, num, #)",
    "role-worker": "Worker",
    "role-owner": "Owner",
    "role-admin": "Admin",
    "user-mgmt-force-reset": "Force-reset password for",
    "user-mgmt-new-pw-placeholder": "New password (8+ chars, num, #)",
    "user-mgmt-pw-reset-title": "🔑 Password reset",
    "user-mgmt-pw-reset-desc": "password has been updated",
    "user-mgmt-edit-username": "Edit username",
    "user-mgmt-err-empty-username": "Username cannot be empty",
    "user-mgmt-err-min3": "Min 3 characters",
    "user-mgmt-err-invalid-username": "Only letters, numbers, underscores",
    "user-mgmt-username-updated": "✅ Username updated",
    "user-mgmt-username-updated-desc": "Renamed to",
    "user-mgmt-loading": "Loading users…",
    "user-mgmt-no-users": "No users found.",
    "user-mgmt-id": "ID",
    "user-mgmt-you": "you",
    "user-mgmt-username": "Username",
    "user-mgmt-role": "Role",
    "user-mgmt-created": "Created",
    "user-mgmt-pw-last-changed": "Password last changed",
    "user-mgmt-never-changed": "Never changed",
    "user-mgmt-last-seen": "Last seen",
    "user-mgmt-shop-id": "Shop ID",
    "user-mgmt-change-role": "Change Role",
    "user-mgmt-reset-pw": "Reset Password",
    "user-mgmt-delete-user": "Delete User",
    "user-mgmt-users-total": "users total",
    "user-mgmt-user-total": "user total",
    "user-mgmt-permanently-delete": "Permanently delete",
    "user-mgmt-cannot-be-undone": "This cannot be undone.",
    "user-mgmt-deleted-title": "🗑 Deleted",
    "user-mgmt-deleted-desc": "removed",
    "user-mgmt-role-updated-title": "Role updated",
    "user-mgmt-role-set-desc": "role set",
    "audit-log-title": "Audit Logs",
    "audit-log-desc": "System-wide activity and security events",
    "audit-timestamp": "Timestamp",
    "audit-action": "Action",
    "audit-actor": "Actor",
    "audit-target": "Target",
    "audit-ip": "IP Address",
    "audit-status": "Status",
    "audit-details": "Details",
    "audit-loading-more": "Loading more log entries...",
    "audit-end-reached": "End of audit trail reached",
    "audit-no-logs": "No audit logs found.",
    "audit-last-updated": "Last updated",
    "audit-unknown-user": "Unknown User",
    "sessions-title": "Active Sessions",
    "sessions-desc": "All currently authenticated devices",
    "sessions-current-device": "Current Device",
    "sessions-revoke-title": "Revoke this session?",
    "sessions-revoke-desc": "The user will be logged out from this device immediately.",
    "sessions-no-active": "No active sessions found.",
    "sessions-revoked-title": "Session Revoked",
    "sessions-revoked-desc": "Session has been terminated successfully.",


    
    // Settings Specific
    "manage-preferences": "Manage preferences, change password and backend configuration",
    "theme-settings": "Theme Settings",
    "choose-theme": "Choose your preferred color scheme",
    "light-mode": "Light Mode",
    "dark-mode": "Dark Mode",
    "system-mode": "System",
    "use-light-theme": "Use light theme",
    "use-dark-theme": "Use dark theme",
    "follow-system-pref": "Follow system preference",
    "language-settings": "Language Settings",
    "choose-language": "Choose your preferred language",
    "use-english-interface": "Use English interface",
    "use-telugu-interface": "Use Telugu interface",
    "app-information": "App Information",
    "mobile-optimization": "Mobile Optimization",
    "touch-optimization": "Touch Optimization",
    "touch-optimization-desc": "Optimize interface for touch devices",
    "auto-sync": "Auto Sync",
    "auto-sync-desc": "Automatically sync when connection is restored",
    "version": "Version",
    "build": "Build",
    "platform": "Platform",
    "last-updated": "Last Updated",
    "new-password": "New Password",
    "current-password": "Current Password",
    "confirm-new-password": "Confirm New Password",
    "enter-current-password": "Enter your current password",
    "enter-new-password": "Enter new password",
    "re-enter-new-password": "Re-enter new password",
    "updating-btn": "Updating…",
    "update-password-btn": "Update Password",
    "strength-weak": "Weak",
    "strength-fair": "Fair",
    "strength-strong": "Strong",
    "mismatch-error": "Passwords do not match",
    "req-fields-error": "All fields required",
    "min-char-error": "Password must be at least 8 characters",
    "num-error": "Password must contain at least one number",
    "spec-error": "Password must contain at least one special character (#@!...)",
    "pw-requirements-desc": "Min 8 characters · at least one number · one special character",
    "setting-saved": "Setting saved",
    "setting-saved-desc": "Your preference has been updated.",
    "pw-success-toast": "Password changed!",
    "pw-success-toast-desc": "Your password has been updated successfully.",
    "error-label": "Error",

    // Common
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    search: "Search",
    filter: "Filter",
    print: "Print",
    send: "Send",
    back: "Back",
    next: "Next",
    finish: "Finish",

    // Auth
    login: "Login",
    logout: "Logout",
    email: "Email",
    password: "Password",
    "remember-me": "Remember me",
    "forgot-password": "Forgot password?",
    "sign-in": "Sign in",

    // Connection
    online: "Online",
    offline: "Offline",
    connecting: "Connecting...",

    // Stock levels
    critical: "Critical",
    low: "Low",
    good: "Good",

    // Repair types
    "screen-replacement": "Screen Replacement",
    "battery-replacement": "Battery Replacement",
    "charging-port": "Charging Port",
    "speaker-repair": "Speaker Repair",
    "camera-repair": "Camera Repair",
    "water-damage": "Water Damage",
    "software-issue": "Software Issue",

    // Payment methods
    cash: "Cash",
    upi: "UPI",
    card: "Card",
    "bank-transfer": "Bank Transfer",
  },
    "error-loading": "Error loading",
    "no-logs": "No audit logs found.",
    "end-reached": "No more logs.",
    "actor": "User",
    "target": "Target",
    "status": "Status",
    "error-revoking-session": "Could not revoke session.",

  te: {
    // Navigation
    dashboard: "డాష్‌బోర్డ్",
    transactions: "లావాదేవీలు",
    suppliers: "సరఫరాదారులు",
    expenditures: "ఖర్చులు",
    bills: "బిల్లులు",
    reports: "నివేదికలు",
    settings: "సెట్టింగ్‌లు",
    admin: "పరిపాలన",
    sales: "అమ్మకాల చరిత్ర",

    // Navigation & Header Extra
    "logged-in-as": "లాగిన్ అయిన యూజర్",
    "sign-out": "లాగ్అవుట్",
    "mobile-tracker": "మొబైల్ రిపేర్ ట్రాకర్",
    "professional-management": "ప్రొఫెషనల్ రిపేర్ మేనేజ్‌మెంట్",
    "system-online": "వ్యవస్థ ఆన్‌లైన్",
    "profile": "ప్రొఫైల్",
    "log-out": "లాగ్ అవుట్",

    // Dashboard
    "today-revenue": "నేటి ఆదాయం",
    "pending-repairs": "పెండింగ్ రిపేర్లు",
    "quick-actions": "త్వరిత చర్యలు",
    "recent-transactions": "ఇటీవలి లావాదేవీలు",
    "new-transaction": "కొత్త లావాదేవీ",
    "record-payment": "చెల్లింపు రికార్డ్",
    "welcome-back": "తిరిగి వచ్చినందుకు స్వాగతం",
    "worker-tasks": "ఇక్కడ మీ రోజువారీ పనులు ఉన్నాయి.",
    "shop-overview": "ఇక్కడ మీ రిపేర్ షాప్ అవలోకనం ఉంది.",
    "loading": "లోడ్ అవుతోంది...",
    "refresh": "రిఫ్రెష్",
    "hide-profits": "లాభాలను దాచు",
    "show-profits": "లాభాలను చూపించు",
    "profit": "లాభం",
    "today-earnings": "నేటి సంపాదన",
    "awaiting-completion": "పూర్తి కావాల్సి ఉంది",
    "latest-repair-jobs": "ఇటీవలి రిపేర్ పనులు",
    "view-all": "అన్నీ చూడు",
    "no-transactions-yet": "ఇంకా ఎలాంటి లావాదేవీలు లేవు",
    "add-first-transaction": "ప్రారంభించడానికి మీ మొదటి రిపేర్ లావాదేవీని జోడించండి",
    "add-transaction": "లావాదేవీని జోడించు",

    // Transactions
    "customer-details": "కస్టమర్ వివరాలు",
    "repair-info": "రిపేర్ వివరాలు",
    "parts-supplier": "భాగాలు & సప్లయర్",
    "additional-details": "అదనపు వివరాలు",
    "customer-name": "కస్టమర్ పేరు",
    "phone-number": "ఫోన్ నంబర్",
    "device-model": "డివైస్ మోడల్",
    "repair-type": "రిపేర్ రకం",
    "repair-cost": "రిపేర్ ఖర్చు",
    "payment-method": "చెల్లింపు పద్ధతి",
    "amount-given": "ఇచ్చిన మొత్తం",
    "change-returned": "తిరిగి ఇచ్చిన డబ్బు",
    "sno": "క్రమ సంఖ్య",
    "txn-id": "లావాదేవీ ID",
    "date-col": "తేదీ",
    "customer-col": "కస్టమర్",
    "device-col": "డివైస్",
    "cost-col": "ఖర్చు",
    "status-col": "స్థితి",
    "actions-col": "చర్యలు",
    "search-placeholder": "లావాదేవీలను వెతకండి...",
    "filter-payment": "చెల్లింపు వడపోత",
    "all-payments": "అన్ని చెల్లింపులు",
    "view-details": "వివరాలను చూడండి",
    "completed": "పూర్తయింది",
    "pending": "పెండింగ్",
    "cancelled": "రద్దు చేయబడింది",
    "manage-repairs-desc": "అన్ని రిపేర్ లావాదేవీలను నిర్వహించండి",
    "transaction-list": "లావాదేవీల జాబితా",
    "txns-found": "లావాదేవీలు కనుగొనబడ్డాయి",
    "export-csv": "CSV ఎగుమతి",
    "download-users": "యూజర్ల డౌన్‌లోడ్",
    "download-transactions": "లావాదేవీల డౌన్‌లోడ్",
    "download-suppliers": "సరఫరాదారుల డౌన్‌లోడ్",

    // Admin & Logs Extra
    "administration": "పరిపాలన",
    "full-system-control": "పూర్తి సిస్టమ్ నియంత్రణ",
    "admin-access-required": "అడ్మిన్ అనుమతి అవసరం",
    "admin-only-message": "నిర్వాహకులు మాత్రమే ఈ పేజీని యాక్సెస్ చేయగలరు.",
    "logged-in-as-status": "లాగిన్ అయిన యూజర్:",
    "stats": "గణాంకాలు",
    "users": "యూజర్లు",
    "perms": "అనుమతులు",
    "audit": "ఆడిట్",
    "export": "ఎగుమతి",
    "api-label": "API",
    "last-updated-at": "చివరిగా అప్‌డేట్ చేయబడింది",
    "audit-desc": "రియల్ టైమ్ సెక్యూరిటీ ఈవెంట్‌లు — లాగిన్ ప్రయత్నాలు, పాస్‌వర్డ్ మార్పులు, పాత్ర అప్‌డేట్‌లు మరియు యూజర్ తొలగింపులు",
    "no-audit-events": "ఇంకా ఎలాంటి ఆడిట్ ఈవెంట్‌లు నమోదు కాలేదు.",
    "timestamp-col": "సమయం",
    "action-col": "చర్య",
    "actor-col": "కర్త",
    "target-col": "లక్ష్యం",
    "ip-col": "IP చిరునామా",
    "details-col": "వివరాలు",
    "end-of-trail": "• ఆడిట్ ట్రయల్ ముగిసింది •",
    "loading-more-logs": "మరిన్ని లాగ్ ఎంట్రీలను లోడ్ చేస్తోంది...",
    "active-sessions-desc": "ప్రస్తుతం సక్రియంగా ఉన్న సెషన్‌లను నిర్వహించండి మరియు అవసరమైతే వాటిని రద్దు చేయండి",
    "current-device": "ప్రస్తుత డివైస్",
    "revoke-session": "రద్దు చేయి",
    "confirm-revoke": "మీరు నిజంగా ఈ సెషన్‌ను రద్దు చేయాలనుకుంటున్నారా?",
    "all-sessions-revoked": "ప్రస్తుత సెషన్ మినహా మిగిలిన అన్ని సెషన్‌లు రద్దు చేయబడ్డాయి",
    "error-loading-sessions": "సెషన్‌లను లోడ్ చేయడంలో లోపం",
    "revoke-session-title": "సెషన్‌ను రద్దు చేయండి",
    "user-mgmt-title": "యూజర్ల నిర్వహణ",
    "user-mgmt-desc": "సిస్టమ్ యూజర్లను నిర్వహించండి, పాస్‌వర్డ్‌లను రీసెట్ చేయండి, పేరు మార్చండి లేదా ఖాతాలను తొలగించండి",

    // UserManagement inline forms
    "new-user-label": "కొత్త యూజర్",
    "create-btn": "సృష్టించు",
    "username-placeholder": "యూజర్ పేరు",
    "password-placeholder": "పాస్‌వర్డ్ (8+ అక్షరాలు, సంఖ్య, #)",
    "reset-pw-title": "పాస్‌వర్డ్ రీసెట్ చేయండి:",
    "new-pw-placeholder": "కొత్త పాస్‌వర్డ్ (8+ అక్షరాలు, సంఖ్య, #)",
    "edit-username-title": "యూజర్ పేరు సవరించండి",
    "new-username-placeholder": "కొత్త యూజర్ పేరు",
    "connection-error": "కనెక్షన్ లోపం",
    "retry": "మళ్లీ ప్రయత్నించండి",
    "loading-users": "యూజర్లను లోడ్ చేస్తోంది...",
    "pw-last-changed": "పాస్‌వర్డ్ చివరగా మార్చిన సమయం",
    "shop-id": "షాప్ ID",
    "reset-password-btn": "పాస్‌వర్డ్ రీసెట్",
    "delete-user-btn": "యూజర్‌ను తొలగించు",
    "change-role-btn": "పాత్రను మార్చండి",
    "confirm-delete-user": "శాశ్వతంగా తొలగించు",
    "confirm-delete-user-suffix": "ఈ చర్యను రద్దు చేయలేము.",
    "you-label": "(మీరు)",
    "never-seen": "ఎప్పుడూ కాదు",
    "just-now": "ఇప్పుడే",
    "active-label": "యాక్టివ్",
    "retrieving-sessions": "సక్రియ సెషన్‌లను పొందుతోంది...",
    "no-sessions-found": "సక్రియ సెషన్‌లు ఏవీ కనుగొనబడలేదు.",
    "user-mgmt-err-req": "యూజర్ పేరు మరియు పాస్‌వర్డ్ తప్పనిసరి",
    "user-mgmt-err-len": "పాస్‌వర్డ్ కనీసం 8 అక్షరాలు ఉండాలి",
    "user-mgmt-err-num": "పాస్‌వర్డ్‌లో కనీసం ఒక అంకె ఉండాలి",
    "user-mgmt-err-spec": "పాస్‌వర్డ్‌లో కనీసం ఒక ప్రత్యేక అక్షరం ఉండాలి",
    "user-mgmt-created-title": "✅ యూజర్ సృష్టించబడ్డారు",
    "user-mgmt-created-desc": "జోడించబడ్డారు",
    "user-mgmt-new-user": "కొత్త యూజర్",
    "user-mgmt-pw-placeholder": "పాస్‌వర్డ్ (8+ అక్షరాలు, అంకె, #)",
    "role-worker": "వర్కర్",
    "role-owner": "ఓనర్",
    "role-admin": "అడ్మిన్",
    "user-mgmt-force-reset": "దీనికోసం పాస్‌వర్డ్ ఫోర్స్-రీసెట్ చేయండి:",
    "user-mgmt-new-pw-placeholder": "కొత్త పాస్‌వర్డ్ (8+ అక్షరాలు, అంకె, #)",
    "user-mgmt-pw-reset-title": "🔑 పాస్‌వర్డ్ రీసెట్ చేయబడింది",
    "user-mgmt-pw-reset-desc": "పాస్‌వర్డ్ నవీకరించబడింది",
    "user-mgmt-edit-username": "యూజర్ పేరును సవరించండి",
    "user-mgmt-err-empty-username": "యూజర్ పేరు ఖాళీగా ఉండకూడదు",
    "user-mgmt-err-min3": "కనీసం 3 అక్షరాలు",
    "user-mgmt-err-invalid-username": "అక్షరాలు, అంకెలు, అండర్‌స్కోర్‌లు మాత్రమే",
    "user-mgmt-username-updated": "✅ యూజర్ పేరు నవీకరించబడింది",
    "user-mgmt-username-updated-desc": "దీనికి పేరు మార్చబడింది:",
    "user-mgmt-loading": "యూజర్‌లను లోడ్ చేస్తోంది…",
    "user-mgmt-no-users": "యూజర్‌లు కనుగొనబడలేదు.",
    "user-mgmt-id": "ఐడి",
    "user-mgmt-you": "మీరు",
    "user-mgmt-username": "యూజర్ పేరు",
    "user-mgmt-role": "పాత్ర",
    "user-mgmt-created": "సృష్టించబడింది",
    "user-mgmt-pw-last-changed": "పాస్‌వర్డ్ చివరిగా మార్చబడింది",
    "user-mgmt-never-changed": "ఎప్పుడూ మార్చబడలేదు",
    "user-mgmt-last-seen": "చివరిగా చూసింది",
    "user-mgmt-shop-id": "షాప్ ఐడి",
    "user-mgmt-change-role": "పాత్ర మార్చండి",
    "user-mgmt-reset-pw": "పాస్‌వర్డ్ రీసెట్ చేయండి",
    "user-mgmt-delete-user": "యూజర్‌ని తొలగించండి",
    "user-mgmt-users-total": "మొత్తం యూజర్‌లు",
    "user-mgmt-user-total": "మొత్తం యూజర్",
    "user-mgmt-permanently-delete": "శాశ్వతంగా తొలగించాలా",
    "user-mgmt-cannot-be-undone": "దీన్ని రద్దు చేయలేరు.",
    "user-mgmt-deleted-title": "🗑 తొలగించబడింది",
    "user-mgmt-deleted-desc": "తొలగించబడ్డారు",
    "user-mgmt-role-updated-title": "పాత్ర నవీకరించబడింది",
    "user-mgmt-role-set-desc": "పాత్ర సెట్ చేయబడింది",
    "audit-log-title": "ఆడిట్ లాగ్‌లు",
    "audit-log-desc": "సిస్టమ్-వ్యాప్త కార్యాచరణ మరియు భద్రతా ఈవెంట్‌లు",
    "audit-timestamp": "సమయం",
    "audit-action": "చర్య",
    "audit-actor": "చేరినవారు",
    "audit-target": "లక్ష్యం",
    "audit-ip": "IP చిరునామా",
    "audit-status": "స్థితి",
    "audit-details": "వివరాలు",
    "audit-loading-more": "మరిన్ని లాగ్ ఎంట్రీలను లోడ్ చేస్తోంది...",
    "audit-end-reached": "ఆడిట్ ట్రైల్ ముగిసింది",
    "audit-no-logs": "ఆడిట్ లాగ్‌లు కనుగొనబడలేదు.",
    "audit-last-updated": "చివరిగా నవీకరించబడింది",
    "audit-unknown-user": "తెలియని యూజర్",
    "sessions-title": "యాక్టివ్ సెషన్‌లు",
    "sessions-desc": "ప్రస్తుతం ప్రామాణీకరించబడిన అన్ని పరికరాలు",
    "sessions-current-device": "ప్రస్తుత పరికరం",
    "sessions-revoke-title": "ఈ సెషన్‌ను ఉపసంహరించాలా?",
    "sessions-revoke-desc": "యూజర్ ఈ పరికరం నుండి వెంటనే లాగ్ అవుట్ చేయబడతారు.",
    "sessions-no-active": "యాక్టివ్ సెషన్‌లు కనుగొనబడలేదు.",
    "sessions-revoked-title": "సెషన్ ఉపసంహరించబడింది",
    "sessions-revoked-desc": "సెషన్ విజయవంతంగా ముగించబడింది.",
    "revoke-session-confirm": "ఈ సెషన్‌ను రద్దు చేయాలా? ఆ పరికరంలో యూజర్ లాగ్అవుట్ అవుతారు.",
    "session-revoked-title": "సెషన్ రద్దు చేయబడింది",
    "session-revoked-desc": "సెషన్ విజయవంతంగా ముగించబడింది.",
    "session-count-suffix": "సక్రియ సెషన్",
    "session-count-plural": "సక్రియ సెషన్‌లు",
    "checked-realtime": "రియల్-టైమ్‌లో తనిఖీ చేయబడింది",
    "total-revenue": "మొత్తం ఆదాయం",
    "total-profit": "మొత్తం లాభం",
    "total-transactions": "మొత్తం లావాదేవీలు",
    "average-transaction-value": "సగటు లావాదేవీ విలువ",
    "completed-transactions": "పూర్తయిన లావాదేవీలు",
    "pending-transactions": "పెండింగ్ లావాదేవీలు",
    "create-user": "యూజర్‌ను సృష్టించు",
    "delete-user": "యూజర్‌ను తొలగించు",
    "no-users-found": "యూజర్లు ఎవరూ కనుగొనబడలేదు.",
    "change-role": "పాత్రను మార్చండి",
    "never-changed": "ఎప్పుడూ మార్చలేదు",
    "total-users": "మొత్తం",
    username: "యూజర్ పేరు",
    role: "పాత్ర",
    created: "సృష్టించబడింది",
    "last-seen": "చివరిసారి చూసింది",
    active: "యాక్టివ్",
    success: "విజయం",
    failed: "విఫలమైంది",
    details: "వివరాలు",
    "ip-address": "IP చిరునామా",
    action: "చర్య",
    timestamp: "సమయం",

    
    // Settings Specific
    "manage-preferences": "ప్రాధాన్యతలు, పాస్‌వర్డ్ మార్పు మరియు బ్యాకెండ్ కాన్ఫిగరేషన్‌ను నిర్వహించండి",
    "theme-settings": "థీమ్ సెట్టింగ్‌లు",
    "choose-theme": "మీకు నచ్చిన రంగుల థీమ్‌ను ఎంచుకోండి",
    "light-mode": "లైట్ మోడ్",
    "dark-mode": "డార్క్ మోడ్",
    "system-mode": "సిస్టమ్ థీమ్",
    "use-light-theme": "లైట్ థీమ్‌ను ఉపయోగించండి",
    "use-dark-theme": "డార్క్ థీమ్‌ను ఉపయోగించండి",
    "follow-system-pref": "సిస్టమ్ ప్రాధాన్యతను అనుసరించండి",
    "language-settings": "భాషా సెట్టింగ్‌లు",
    "choose-language": "మీకు నచ్చిన భాషను ఎంచుకోండి",
    "use-english-interface": "ఇంగ్లీష్ ఇంటర్‌ఫేస్ ఉపయోగించండి",
    "use-telugu-interface": "తెలుగు భాషలో ఉపయోగించండి",
    "app-information": "యాప్ సమాచారం",
    "mobile-optimization": "మొబైల్ ఆప్టిమైజేషన్",
    "touch-optimization": "టచ్ ఆప్టిమైజేషన్",
    "touch-optimization-desc": "టచ్ పరికరాల కోసం ఇంటర్‌ఫేస్‌ను ఆప్టిమైజ్ చేయండి",
    "auto-sync": "ఆటోమేటిక్ సింక్",
    "auto-sync-desc": "కనెక్షన్ పునరుద్ధరించబడినప్పుడు ఆటోమేటిక్‌గా సింక్ చేయండి",
    "version": "వెర్షన్",
    "build": "బిల్డ్",
    "platform": "ప్లాట్‌ఫారమ్",
    "last-updated": "చివరిగా నవీకరించబడింది",
    "new-password": "కొత్త పాస్‌వర్డ్",
    "current-password": "ప్రస్తుత పాస్‌వర్డ్",
    "confirm-new-password": "కొత్త పాస్‌వర్డ్‌ను నిర్ధారించండి",
    "enter-current-password": "మీ ప్రస్తుత పాస్‌వర్డ్‌ను నమోదు చేయండి",
    "enter-new-password": "కొత్త పాస్‌వర్డ్‌ను నమోదు చేయండి",
    "re-enter-new-password": "కొత్త పాస్‌వర్డ్‌ను మళ్లీ నమోదు చేయండి",
    "updating-btn": "నవీకరిస్తోంది...",
    "update-password-btn": "పాస్‌వర్డ్‌ను నవీకరించండి",
    "strength-weak": "బలహీనంగా ఉంది",
    "strength-fair": "పర్వాలేదు",
    "strength-strong": "బలంగా ఉంది",
    "mismatch-error": "పాస్‌వర్డ్‌లు సరిపోలడం లేదు",
    "req-fields-error": "అన్ని ఫీల్డ్‌లు తప్పనిసరి",
    "min-char-error": "పాస్‌వర్డ్ కనీసం 8 అక్షరాలు ఉండాలి",
    "num-error": "పాస్‌వర్డ్‌లో కనీసం ఒక నంబర్ ఉండాలి",
    "spec-error": "పాస్‌వర్డ్‌లో కనీసం ఒక ప్రత్యేక అక్షరం ఉండాలి (#@!...)",
    "pw-requirements-desc": "కనీసం 8 అక్షరాలు · కనీసం ఒక నంబర్ · ఒక ప్రత్యేక అక్షరం",
    "setting-saved": "సెట్టింగ్ సేవ్ చేయబడింది",
    "setting-saved-desc": "మీ ప్రాధాన్యత విజయవంతంగా అప్‌డేట్ చేయబడింది.",
    "pw-success-toast": "పాస్‌వర్డ్ మార్చబడింది!",
    "pw-success-toast-desc": "మీ పాస్‌వర్డ్ విజయవంతంగా నవీకరించబడింది.",
    "error-label": "లోపం",

    // Common
    save: "சேవ్",
    cancel: "రద్దు",
    edit: "ఎడిట్",
    delete: "తొలగించు",
    search: "వెతుకు",
    filter: "ఫిల్టర్",
    print: "ప్రింట్",
    send: "పంపు",
    back: "వెనుకకు",
    next: "తదుపరి",
    finish: "పూర్తి",

    // Auth
    login: "లాగిన్",
    logout: "లాగ్అవుట్",
    email: "ఈమెయిల్",
    password: "పాస్‌వర్డ్",
    "remember-me": "నన్ను గుర్తుంచుకో",
    "forgot-password": "పాస్‌వర్డ్ మర్చిపోయారా?",
    "sign-in": "లాగిన్ అవ్వండి",

    // Connection
    online: "ఆన్‌లైన్",
    offline: "ఆఫ్‌లైన్",
    connecting: "కనెక్ట్ అవుతోంది...",

    // Stock levels
    critical: "క్రిటికల్",
    low: "తక్కువ",
    good: "బాగుంది",

    // Repair types
    "screen-replacement": "స్క్రీన్ రీప్లేస్‌మెంట్",
    "battery-replacement": "బ్యాటరీ రీప్లేస్‌మెంట్",
    "charging-port": "చార్జింగ్ పోర్ట్",
    "speaker-repair": "స్పీకర్ రిపేర్",
    "camera-repair": "కెమెరా రిపేర్",
    "water-damage": "నీటి నష్టం",
    "software-issue": "సాఫ్ట్‌വേర్ సమస్య",

    // Payment methods
    cash: "నగదు",
    upi: "UPI",
    card: "కార్డ్",
    "bank-transfer": "బ్యాంక్ బదిలీ",
  },};

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined,
);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      return (localStorage.getItem("language") as Language) || "en";
    }
    return "en";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
    document.documentElement.lang = language;

    // Add Telugu class for font support
    if (language === "te") {
      document.documentElement.classList.add("telugu");
    } else {
      document.documentElement.classList.remove("telugu");
    }
  }, [language]);

  const t = (key: string): string => {
    return (
      translations[language][
        key as keyof (typeof translations)[typeof language]
      ] || key
    );
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}